package GameProject;

public class QuestionBank {
	
	public static final Question[] QList = {
			 new Question( "Which animal is known as the 'King of the Jungle'?",
					 	"Elephant", "Tiger", "Lion", "Bear", 2, 1),
			 new Question( "What is the process by which plants convert carbon dioxide and water into glucose and oxygen using sunlight?",
					 	"Cellular Respiration", "Fermentation", "Phototropism", "Photosynthesis ", 3, 1),
			 new Question( "What is the capital city of France?", 
					 	"Paris", "Berlin", "Rome", "Madrid", 0, 1),
			 new Question( "Which planet is known as the Red Planet?",
				 		"Venus", "Jupiter", "Mercury", "Mars", 3, 1),
			 new Question( "What is the largest mammal in the world?",
					 	"Elephant", "Giraffe", "Blue Whale", "Rhino", 2, 1),
			 new Question( "In which continent is the Sahara Desert located?",
					 	"Australia", "Africa", "Asia", "South America", 1, 1),
			 new Question( "Which ocean is the largest?",
					 	"Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", 0, 1),
			 new Question( "Who wrote the play 'Romeo and Juliet'?",
					 	"William Shakespeare", "Charles Dickens", "Jane Austen", "George Orwell", 0, 1),
			 new Question( "What is the chemical symbol for gold?",
					 	"Ag", "Au", "Go", "Gd", 1, 1 ),
			 new Question( "Who painted the Mona Lisa?",
					 	"Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo", 2, 1),
			 
			 
			 new Question( "Which planet is the closest to Earth?",
						"Mars", "Venus", "Mercury", "Jupiter", 1, 2),
			 new Question( "What is the capital of Australia?",
						"Sydney", "Melbourne", "Brisbane", "Canberra", 3, 2),
			 new Question( "In Harry Potter, what is the name of Harry's pet owl?",
						"Hedwig", "Crookshanks", "Scabbers", "Fang", 0, 2),
			 new Question( "Who is the author of the novel '1984'?",
						"Aldous Huxley", "George Orwell", "J.R.R. Tolkien", "Stephen King", 1, 2),
			 new Question( "Which organ in the human body produces insulin?",
						"Liver", "Kidney", "Stomach", "Pancreas", 3, 2),
			 new Question( "What is the capital city of Spain?",
						"Barcelona", "Seville", "Madrid", "Valencia", 2, 2),
			 new Question( "In mathematics, what is the name for a polygon with nine sides?",
						"Heptagon", "Nonagon", "Octagon", "Decagon", 1, 2),
			 new Question( "In Greek mythology, who is the god of the sea?",
						"Poseidon", "Zeus", "Apollo", "Hermes", 0, 2 ),
			 new Question( "What is the longest river in the world?",
						"Yangtze River", "Nile River", "Amazon River", "Mississippi River", 1, 2),
			 new Question( "What is the capital of Iceland?",
						"Helsinki", "Oslo", "Reykjavik", "Copenhagen", 2, 2),
			 
			 
			 new Question( "Who wrote the novel \"Pride and Prejudice\"?",
						"Mary Shelley", "Charlotte Brontë", " Emily Dickinson", "Jane Austen", 3, 3),
			 new Question( "In which country can you find the ancient city of Machu Picchu?",
						"Brazil", "Peru", "Chile", "Argentina",1, 3),
			 new Question( "Who composed the Four Seasons?",
						"Ludwig van Beethoven", "Antonio Vivaldi", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach",1, 3),
			 new Question( "What is the main language spoken in Brazil?",
						"Portuguese", "Spanish", "English", "Brazillian",0, 3),
			 new Question( "Who is the artist behind the painting \"The Starry Night\"?",
						"Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí",2, 3),
			 new Question( "In what year did the Titanic sink?",
						"1905", "1923", "1931", "1912",3, 3),
			 new Question( "Who was the first person to propose the concept of a heliocentric solar system?",
						"Nicolaus Copernicus", "Galileo Galilei", "Johannes Kepler", "Isaac Newton",0, 3),
			 new Question( "In which year did the Berlin Wall fall?",
						"1987", "1989", "1991", "1994",1, 3),
			 new Question( "Which scientist first discovered the circulation of blood in the human body?",
						"William Harvey", "Isaac Newton", "Galileo Galilei", "Charles Darwin",0, 3),
			 new Question( "What is the capital city of South Africa?",
						"Johannesburg", "Pretoria", "Cape Town", "Durban",1, 3),
			 
				
			 new Question( "Who wrote \"The Republic\", a philosophical text?",
						"Aristotle", "Plato", "Socrates", "Euripides", 1, 4),
			 new Question( "Which element has the atomic number 79?",
						"Iron", "Silver", "Platinum", "Gold", 3, 4 ),
			 new Question( "Who composed the music for the ballet \"Swan Lake\"?",
						"Johann Sebastian Bach", "Pyotr Ilyich Tchaikovsky", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", 1, 4 ),
			 new Question( "Which U.S. president appears on the $20 bill?",
						"George Washington", "Abraham Lincoln", "Alexander Hamilton", "Andrew Jackson",3, 4),
			 new Question( "In what year was the first iPhone released?",
						"2005", "2009", "2007", "2011", 2, 4 ),
			 new Question( "Which Shakespearean play features the characters of Goneril, Regan, and Cordelia?",
						"King Lear", "Macbeth", "Hamlet", "Othello", 0, 4),
			 new Question( "Which element is named after the creator of the periodic table?",
						"Curium", "Einsteinium", "Mendelevium", "Bohrium", 2, 4),
			 new Question( "What is the largest moon of Saturn?",
						"Europa", "Ganymede", "Titan", "Callisto", 2, 4),
			 new Question( "Which river flows through Paris?",
						"Thames", "Danube", "Rhine", "Seine", 3, 4),
			 new Question( "In which city was the first modern Olympic Games held?",
						"Athens", "Paris", "London", "Rome", 0, 2 ),
			 
			 
			 new Question( "Which architect designed the Guggenheim Museum in Bilbao, Spain?",
						"Frank Gehry", "Frank Lloyd Wright", "I.M. Pei", "Zaha Hadid",0, 5),
			 new Question( "Who wrote the epic poem \"Paradise Lost\"?",
						"William Shakespeare", "John Milton", "Geoffrey Chaucer", "John Donne",1, 5),
			 new Question( "What is the heaviest naturally occurring element found on Earth?",
						"Uranium", "Osmium", "Iridium", "Plutonium",0, 5),
			 new Question( "Which element has the highest melting point?",
						"Iron", "Carbon", "Tungsten ", "Uranium", 2, 5),
			 new Question( "In which country is the ancient city of Petra located?",
						"Jordan", "Egypt", "Greece", "Iran", 0, 5),
			 new Question( "Which philosopher coined the phrase \"I think, therefore I am\"?",
						"Socrates", "Plato", "Aristotle", "René Descartes", 3, 5),
			 new Question( "Who composed the \"Moonlight Sonata\"?",
						"Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Johann Sebastian Bach", "Franz Schubert", 1, 5),
			 new Question( "What is the study of fungi called?", 
					 	"Botany", "Entomology", "Mycology", "Ecology", 2, 5 ),
			 new Question( "Which author wrote \"Brave New World\"?",
						"George Orwell", "Ray Bradbury", "H.G. Wells", "Aldous Huxley",3, 5),
			 new Question( "The Battle of Hastings in 1066 was fought in which country?",
						"France", "Germany", "England", "Spain", 2, 5),
			 
			 
			 
			 
			 new Question( "In music, which term indicates a tempo that is faster than \"allegro\"?",
						"Andante", "Presto", "Lento", "Adagio",1, 6),
			 new Question( "Who was the first female Prime Minister of the United Kingdom?",
						"Theresa May", "Angela Merkel", "Margaret Thatcher", "Indira Gandhi",2, 6),
			 new Question( "What is the largest internal organ in the human body?",
						"Heart", "Brain", "Lung", "Liver",3, 6),
			 new Question( "The novel \"Crime and Punishment\" was written by which author?",
						"Leo Tolstoy", "Fyodor Dostoevsky ", "Anton Chekhov", "Vladimir Nabokov",1, 6),
			 new Question( "Which painting was stolen from the Isabella Stewart Gardner Museum in the infamous 1990 art heist",
						"The Storm on the Sea of Galilee", "The Mona Lisa", "Starry Night", "Girl with a Pearl Earring",0, 6),
			 new Question( "What is the capital of Lithuania?",
						"Vilnius", "Riga", "Tallinn", "Minsk",0, 6),
			 new Question( "Which philosopher is famous for the quote \"Man is condemned to be free\"?",
						"Friedrich Nietzsche", "Louis Pasteur", "Jean-Paul Sartre", "Gregor Mendel",2, 6),
			 new Question( "Which scientist is credited with the discovery of penicillin?",
						"Marie Curie", "Louis Pasteur", "Gregor Mendel", "Alexander Fleming",3, 6),
			 new Question( "The ancient city of Carthage was located in the present-day territory of which country?",
						"Tunisia", "Egypt", "Greece", "Italy",0, 6),
			 new Question( "Who is considered the father of modern taxonomy?",
						"Charles Darwin", "Gregor Mendel", "Carl Linnaeus", "Louis Pasteur",2, 6),
				
			 
			 
			 new Question( "The Battle of Waterloo in 1815 marked the defeat of which historical figure?",
						"Julius Caesar", "Alexander the Great", "Genghis Khan", "Napoleon Bonaparte",3, 7),
			 new Question( "Who was the Greek goddess of wisdom?",
						"Athena", "Aphrodite", "Hera", "Artemis",0, 7),
			 new Question( "What is the capital of Brazil?",
						"Rio de Janeiro", "São Paulo", "Brasília", "Buenos Aires",2, 7),
			 new Question( "Who composed the \"Brandenburg Concertos\"?",
						"Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonio Vivaldi",1, 7),
			 new Question( "What is the capital of Mongolia?",
						"Ulaanbaatar", "Astana", "Bishkek", "Kathmandu",0, 7),
			 new Question( "Who wrote the symphony \"The Lark Ascending\"?",
						"Edward Elgar", "Gustav Holst", "Ralph Vaughan Williams", "Benjamin Britten", 2, 7),
			 new Question( "Who is the author of the book \"A Brief History of Time\"?",
						"Stephen Hawking", "Carl Sagan", "Neil deGrasse Tyson", "Richard Feynman", 0, 7),
			 new Question( "Which physicist developed the theory of color based on the observation of a prism?",
						"Albert Einstein", "Niels Bohr", "Isaac Newton ", "Max Planck", 2, 7),
			 new Question( "Which artist is known for the sculpture \"The Thinker\"?",
						"Michelangelo", "Rodin", "Donatello", "Bernini",1, 7),
			 new Question( "Which country is the origin of the Merino breed of sheep, known for its wool?",
						"New Zealand", "Scotland", "Ireland", "Australia",3, 7),
			 
			 
			 
			 
			 new Question( "In which city was the Treaty of Versailles signed in 1919?",
						"Berlin", "London", "Vienna", "Paris",3, 8),
			 new Question( "In which year was the Nobel Prize in Literature first awarded?",
						"1895", "1901", "1910", "1923",1, 8),
			 new Question( "Who composed the opera \"Madama Butterfly\"?",
						"Wolfgang Amadeus Mozart", "Giacomo Puccini", "Ludwig van Beethoven", "Giuseppe Verdi",1, 8),
			 new Question( "The ruins of the ancient city of Persepolis are in which country?",
						"Greece", "Egypt", "Iraq", "Iran",3, 8),
			 new Question( "In art, what is the term used for a technique that creates the appearance of three dimensions on a flat surface?",
						"Trompe-l'œil", "Cubism", "Impressionism", "Surrealism",0, 8),
			 new Question( "Which philosopher wrote \"Critique of Pure Reason\"?",
						"Friedrich Nietzsche", "Søren Kierkegaard", "Immanuel Kant", "David Hume",2, 8),
			 new Question( "In which century was the first mechanical clock invented?",
						"11th Century", "14th Century", "16th Century", "18th Century",1, 8),
			 new Question( "Which king signed the Magna Carta in 1215?",
						"King Henry VIII", "King Richard I", "King Edward I", "King John",3, 8),
			 new Question( "The ancient Library of Alexandria was located in which country?",
						"Egypt", "Greece", "Italy", "Turkey",0, 8),
			 new Question( "The Hagia Sophia in Istanbul was originally built as what type of building?",
						"Mosque", "Palace", "Cathedral", "Library",2, 8),
			 
			 
			 
			 
			 new Question( "Which philosopher is known for the existential concept of \"The Absurd\"?",
						"Jean-Paul Sartre", "Friedrich Nietzsche", "Søren Kierkegaard", "Albert Camus", 3, 8),
			 new Question( "The Potala Palace, a UNESCO World Heritage Site, is located in which city?",
						"Kathmandu", "Bhutan", "Lhasa", "Shigatse", 2, 8 ),
			 new Question( "The Treaty of Tordesillas, signed in 1494, divided the newly discovered lands outside Europe between which two countries?",
						"Spain and Portugal", "England and France", "Spain and France", "Portugal and England", 0, 8 ),
			 new Question( "What is the name of the first spacecraft to land on a comet?",
						"Voyager 1", "New Horizons", "Rosetta", "Cassini", 2, 8 ),
			 new Question( "What is the capital of Burkina Faso?",
						"Bamako", "Niamey", "N'Djamena", "Ouagadougou", 3, 8 ),
			 new Question( "Who wrote the existentialist work \"Being and Time\"?",
						"Jean-Paul Sartre", "Martin Heidegger", "Friedrich Nietzsche", "Albert Camus", 1, 8 ),
			 new Question( "In which year was the element Oganesson first synthesized?",
						"2002", "2010", "2014", "2006", 3, 8 ),
			 new Question( "The ancient city of Nineveh was located in the modern-day territory of which country?",
						"Iraq", "Iran", "Egypt", "Syria", 0, 8),
	};
	
	public QuestionBank() {}
}
